version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: samlion
      POSTGRES_PASSWORD: 333693
      POSTGRES_DB: flaskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mynet

volumes:
  postgres_data:

networks:
  mynet:
