version: '3.8'

services:
  web:
    build:
      context: .
    container_name: flask-app
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/code
    working_dir: /code  
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SQLALCHEMY_DATABASE_URI=postgresql://samlion:333693@db:5432/flaskdb

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: samlion
      POSTGRES_PASSWORD: 333693
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
