"""Добавил заявку друзья

Revision ID: 06743a255a6f
Revises: 541d9e4d06b5
Create Date: 2025-07-10 12:41:54.155082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06743a255a6f'
down_revision: Union[str, Sequence[str], None] = '541d9e4d06b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_request', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend_request', 'status')
    # ### end Alembic commands ###
