"""добавил игнор пользователей

Revision ID: e04b02ac60bc
Revises: 8dbf78727918
Create Date: 2025-07-14 10:41:55.237536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04b02ac60bc'
down_revision: Union[str, Sequence[str], None] = '8dbf78727918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ignored_users',
    sa.Column('ignorer_id', sa.Integer(), nullable=True),
    sa.Column('ignored_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ignored_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ignorer_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ignored_users')
    # ### end Alembic commands ###
